name:                sperg
version:             0.1.0.0
github:              "holzmanj/sperg"
license:             BSD3
author:              "Jesse Holzman"
maintainer:          "jesseholzman96@gmail.com"
copyright:           "2020 Jesse Holzman"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/holzmanj/sperg#readme>

dependencies:
- base >= 4.7 && < 5
- array
- containers
- mtl

library:
  source-dirs: src

executables:
  sperg-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sperg

tests:
  sperg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sperg
