{-# LANGUAGE CPP #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif
{-# LANGUAGE FlexibleInstances #-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for PrintGrammar.
--   Generated by the BNF converter.

module PrintGrammar where

import qualified AbsGrammar
import Data.Char

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    [";"]        -> showChar ';'
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i     = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsGrammar.Ident where
  prt _ (AbsGrammar.Ident i) = doc $ showString $ i
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x, doc (showString "|")]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsGrammar.Prog where
  prt i e = case e of
    AbsGrammar.Program stmts -> prPrec i 0 (concatD [prt 0 stmts])

instance Print [AbsGrammar.Stmt] where
  prt = prtList

instance Print AbsGrammar.Stmt where
  prt i e = case e of
    AbsGrammar.SBind id expr -> prPrec i 0 (concatD [doc (showString "let"), prt 0 id, doc (showString "="), prt 0 expr])
  prtList _ [] = concatD []
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString "\n"), prt 0 xs]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print [AbsGrammar.Expr] where
  prt = prtList

instance Print AbsGrammar.Expr where
  prt i e = case e of
    AbsGrammar.EIdent id -> prPrec i 10 (concatD [prt 0 id])
    AbsGrammar.ELit lit -> prPrec i 10 (concatD [prt 0 lit])
    AbsGrammar.EDefer -> prPrec i 10 (concatD [doc (showString "@")])
    AbsGrammar.EApply expr1 expr2 -> prPrec i 9 (concatD [prt 9 expr1, prt 10 expr2])
    AbsGrammar.EForce expr -> prPrec i 8 (concatD [doc (showString "!"), prt 9 expr])
    AbsGrammar.EMul expr1 expr2 -> prPrec i 7 (concatD [prt 7 expr1, doc (showString "*"), prt 8 expr2])
    AbsGrammar.EDiv expr1 expr2 -> prPrec i 7 (concatD [prt 7 expr1, doc (showString "/"), prt 8 expr2])
    AbsGrammar.EMod expr1 expr2 -> prPrec i 7 (concatD [prt 7 expr1, doc (showString "%"), prt 8 expr2])
    AbsGrammar.EAdd expr1 expr2 -> prPrec i 6 (concatD [prt 6 expr1, doc (showString "+"), prt 7 expr2])
    AbsGrammar.ESub expr1 expr2 -> prPrec i 6 (concatD [prt 6 expr1, doc (showString "-"), prt 7 expr2])
    AbsGrammar.ECons expr1 expr2 -> prPrec i 5 (concatD [prt 6 expr1, doc (showString "::"), prt 5 expr2])
    AbsGrammar.ELess expr1 expr2 -> prPrec i 4 (concatD [prt 5 expr1, doc (showString "<"), prt 5 expr2])
    AbsGrammar.EMore expr1 expr2 -> prPrec i 4 (concatD [prt 5 expr1, doc (showString ">"), prt 5 expr2])
    AbsGrammar.ELessEq expr1 expr2 -> prPrec i 4 (concatD [prt 5 expr1, doc (showString "<="), prt 5 expr2])
    AbsGrammar.EMoreEq expr1 expr2 -> prPrec i 4 (concatD [prt 5 expr1, doc (showString ">="), prt 5 expr2])
    AbsGrammar.EEqual expr1 expr2 -> prPrec i 4 (concatD [prt 5 expr1, doc (showString "=="), prt 5 expr2])
    AbsGrammar.ENEqual expr1 expr2 -> prPrec i 4 (concatD [prt 5 expr1, doc (showString "!="), prt 5 expr2])
    AbsGrammar.EAnd expr1 expr2 -> prPrec i 3 (concatD [prt 4 expr1, doc (showString "and"), prt 3 expr2])
    AbsGrammar.EOr expr1 expr2 -> prPrec i 2 (concatD [prt 3 expr1, doc (showString "or"), prt 2 expr2])
    AbsGrammar.EShove expr1 expr2 -> prPrec i 1 (concatD [prt 1 expr1, doc (showString "->"), prt 2 expr2])
    AbsGrammar.EIfThen expr1 expr2 expr3 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 expr1, doc (showString "then"), prt 0 expr2, doc (showString "else"), prt 0 expr3])
    AbsGrammar.ELetIn binds expr -> prPrec i 0 (concatD [doc (showString "let"), prt 0 binds, doc (showString "in"), prt 0 expr])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsGrammar.Lit where
  prt i e = case e of
    AbsGrammar.LInt n -> prPrec i 0 (concatD [prt 0 n])
    AbsGrammar.LDouble d -> prPrec i 0 (concatD [prt 0 d])
    AbsGrammar.LChar c -> prPrec i 0 (concatD [prt 0 c])
    AbsGrammar.LString str -> prPrec i 0 (concatD [prt 0 str])
    AbsGrammar.LTrue -> prPrec i 0 (concatD [doc (showString "true")])
    AbsGrammar.LFalse -> prPrec i 0 (concatD [doc (showString "false")])
    AbsGrammar.LVoid -> prPrec i 0 (concatD [doc (showString "void")])
    AbsGrammar.LList exprs -> prPrec i 0 (concatD [doc (showString "["), prt 0 exprs, doc (showString "]")])
    AbsGrammar.LLambda ids expr -> prPrec i 0 (concatD [doc (showString "{"), prt 0 ids, prt 0 expr, doc (showString "}")])

instance Print [AbsGrammar.Ident] where
  prt = prtList

instance Print [AbsGrammar.Bind] where
  prt = prtList

instance Print AbsGrammar.Bind where
  prt i e = case e of
    AbsGrammar.Bind id expr -> prPrec i 0 (concatD [prt 0 id, doc (showString "="), prt 0 expr])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

